server:
  port: 80

#是否启用接口文档 是 true 否 false
swagger2:
  enable: true

spring:
  application:
    name: multi-api
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB # 最大支持文件大小
      max-request-size: 200MB # 最大支持请求大小

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.113:3306/a_wt?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456Ab
    # Hikari will use the above plus the following to setup connection pooling
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.multi.pojo.**.**